import random

PROTOSS_ACTIONS = [
    "TRAIN PROBE",
    "TRAIN ZEALOT",
    "TRAIN ADEPT",
    "TRAIN STALKER",
    "TRAIN SENTRY",
    "TRAIN HIGHTEMPLAR",
    "TRAIN DARKTEMPLAR",
    "TRAIN VOIDRAY",
    "TRAIN CARRIER",
    "TRAIN TEMPEST",
    "TRAIN ORACLE",
    "TRAIN PHOENIX",
    "TRAIN MOTHERSHIP",
    "TRAIN OBSERVER",
    "TRAIN IMMORTAL",
    "TRAIN WARPPRISM",
    "TRAIN COLOSSUS",
    "TRAIN DISRUPTOR",
    "MORPH ARCHON",
    "BUILD PYLON",
    "BUILD ASSIMILATOR",
    "BUILD NEXUS",
    "BUILD GATEWAY",
    "BUILD CYBERNETICSCORE",
    "BUILD FORGE",
    "BUILD TWILIGHTCOUNCIL",
    "BUILD ROBOTICSFACILITY",
    "BUILD STARGATE",
    "BUILD TEMPLARARCHIVE",
    "BUILD DARKSHRINE",
    "BUILD ROBOTICSBAY",
    "BUILD FLEETBEACON",
    "BUILD PHOTONCANNON",
    "BUILD SHIELDBATTERY",
    "RESEARCH WARPGATERESEARCH",
    "RESEARCH PROTOSSAIRWEAPONSLEVEL1",
    "RESEARCH PROTOSSAIRWEAPONSLEVEL2",
    "RESEARCH PROTOSSAIRWEAPONSLEVEL3",
    "RESEARCH PROTOSSAIRARMORSLEVEL1",
    "RESEARCH PROTOSSAIRARMORSLEVEL2",
    "RESEARCH PROTOSSAIRARMORSLEVEL3",
    "RESEARCH ADEPTPIERCINGATTACK",
    "RESEARCH BLINKTECH",
    "RESEARCH CHARGE",
    "RESEARCH PROTOSSGROUNDWEAPONSLEVEL1",
    "RESEARCH PROTOSSGROUNDWEAPONSLEVEL2",
    "RESEARCH PROTOSSGROUNDWEAPONSLEVEL3",
    "RESEARCH PROTOSSGROUNDARMORSLEVEL1",
    "RESEARCH PROTOSSGROUNDARMORSLEVEL2",
    "RESEARCH PROTOSSGROUNDARMORSLEVEL3",
    "RESEARCH PROTOSSSHIELDSLEVEL1",
    "RESEARCH PROTOSSSHIELDSLEVEL2",
    "RESEARCH PROTOSSSHIELDSLEVEL3",
    "RESEARCH EXTENDEDTHERMALLANCE",
    "RESEARCH GRAVITICDRIVE",
    "RESEARCH OBSERVERGRAVITICBOOSTER",
    "RESEARCH PSISTORMTECH",
    "RESEARCH VOIDRAYSPEEDUPGRADE",
    "RESEARCH PHOENIXRANGEUPGRADE",
    "RESEARCH TEMPESTGROUNDATTACKUPGRADE",
    "SCOUTING PROBE",
    "SCOUTING OBSERVER",
    "SCOUTING ZEALOT",
    "SCOUTING PHOENIX",
    "MULTI-ATTACK",
    "MULTI-RETREAT",
    "CHRONOBOOST NEXUS",
    "CHRONOBOOST CYBERNETICSCORE",
    "CHRONOBOOST TWILIGHTCOUNCIL",
    "CHRONOBOOST STARGATE",
    "CHRONOBOOST FORGE",
    "EMPTY ACTION",
]

NUM_ACTIONS = 5


class RandomStarCraftAgent:
    TRACK = "TRACK1"

    def __init__(self, **kwargs):
        pass

    def act(self, obs, **kwargs) -> str:
        actions = [random.choice(PROTOSS_ACTIONS) for _ in range(NUM_ACTIONS)]
        return "\n".join(f"{i + 1}: {a}" for i, a in enumerate(actions))
