# @package _global_

ENV: ${oc.env:ENV, "dev"}
CWD: ${hydra:runtime.cwd}
LOG_LEVEL: ${oc.env:LOG_LEVEL, "DEBUG"}

defaults:
  - _self_
  - twenty_fourty_eight: base
  - super_mario: base
  - pokemon_red: base
  - override twenty_fourty_eight/agent: macla_gemini
  - override super_mario/agent: macla_gemini 
  - override pokemon_red/agent: macla_gemini