class_name: "agents.macla.unified.UnifiedMaclaAgent"
model: gemini-2.5-pro
temperature: 1.0
gcp_location: "europe-west1"
thinking_level: "high"
game_config_path: "super_mario"
track: "TRACK2"
macla_max_theta: 0.1
